version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.prod
    ports:
      - "8080:3001"
    env_file:
      - packages/db/.env

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile.prod
    ports:
      - "3000:3000"
    depends_on:
      - api