FROM node:22

WORKDIR /app

RUN corepack enable
RUN corepack prepare pnpm@9.15.0 --activate

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.base.json ./

COPY apps ./apps
COPY packages ./packages

RUN pnpm install

RUN pnpm --filter db build
RUN pnpm --filter api build

WORKDIR /app/apps/api

EXPOSE 3001

CMD ["node", "dist/index.js"]